// <auto-generated />
using System;
using DataBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PolesDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806174737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DataBase.Model.Employment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmploeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmploeeId");

                    b.ToTable("Employments");
                });

            modelBuilder.Entity("DataBase.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Earnings")
                        .HasColumnType("int");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DataBase.Model.Company", b =>
                {
                    b.HasOne("DataBase.Model.Person", "Boss")
                        .WithMany()
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("DataBase.Model.Employment", b =>
                {
                    b.HasOne("DataBase.Model.Company", "Company")
                        .WithMany("Employed")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataBase.Model.Person", "Emploee")
                        .WithMany("Employments")
                        .HasForeignKey("EmploeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Domain.Common.Contract", "Contract", b1 =>
                        {
                            b1.Property<int>("EmploymentId")
                                .HasColumnType("int");

                            b1.Property<string>("ContractType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Contract");

                            b1.HasKey("EmploymentId");

                            b1.ToTable("Employments");

                            b1.WithOwner()
                                .HasForeignKey("EmploymentId");
                        });

                    b.Navigation("Company");

                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("Emploee");
                });

            modelBuilder.Entity("DataBase.Model.Person", b =>
                {
                    b.HasOne("DataBase.Model.Person", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataBase.Model.Person", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataBase.Model.Person", "Partner")
                        .WithMany("Children")
                        .HasForeignKey("PartnerId");

                    b.OwnsOne("DataBase.Model.Gender", "Gender", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Gender");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Father");

                    b.Navigation("Gender")
                        .IsRequired();

                    b.Navigation("Mother");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("DataBase.Model.Company", b =>
                {
                    b.Navigation("Employed");
                });

            modelBuilder.Entity("DataBase.Model.Person", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Employments");
                });
#pragma warning restore 612, 618
        }
    }
}
